wso2-extensions/identity-oauth2-grant-jwt

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
I added few more methods to be able to cover more scenarios:
- Ability to customize subject resolution
- Ability to integrate with public key databases
> Provided capability to resolve client certificate and subject

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Refer : https://wso2.org/jira/browse/ISCONNECT-62
> ISCONNECT-62 : Improve JWT Grant to handle the case where 'default' IDP is returned

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Fix OpenID connect token spec violation when we try to get JWT Bearer Grant working
> IDENTITY-5888: Fix OpenID connect token spec violation when we try to get JWT Bearer Grant working with Resident IDP

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- https://wso2.org/sonar/component_issues/index?id=org.wso2.carbon.extension.identity.oauth2.grantType.jwt%3Aidentity-inbound-oauth2-grant-jwt#severities=CRITICAL
ASAP
- Should Run the integration test once merged.
> Critical and Blocker SonarQube issue fixes

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Fixing a bug where an exception is thrown when debug logs are disabled.
Immediate.
N/A
> IDENTITY-6158 - Exception thrown when debug logs are disabled

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/internal/JWTServiceComponent.java
- Fix package in maven bundle plugin
- Remove service registration at activate method 
- ASAP
- N/A
> Fix OSGI package issue

- feature/pom.xml
This fixes the feature id issue in the pom. This does not allow the feature to be installed from p2-profile
> Fix feature id name

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTConstants.java
- pom.xml
Part of fix for wso2/product-is#3140
**Needs to be merged after merging** https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/879 and https://github.com/wso2/orbit/pull/315
> Add support for JWKS based JWT validation:

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTConstants.java
- component/grant-type/src/test/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandlerTest.java
- component/grant-type/src/test/resources/testng.xml
- pom.xml
- Currently custom claims are not handled properly in JWT bearer grant handler. This PR add support for -  passing the custom claims from JWT grant handler level.
- Related issue wso2/product-is#3183
- Related PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/892
This should be merged after merging https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/892 and after updating oauth version.
N/A
-
> Add support for custom claims

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Support for encrypted JWT in jwt bearer grant type
> Support for encrypted JWT in jwt bearer grant type

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Remove custom claim persistance
> Remove custom claim persistance

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- Resolves https://github.com/wso2/product-is/issues/4523
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-
> Fix issue #4523

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- pom.xml
Resolves https://github.com/wso2/product-is/issues/5713
The id token retrieved through JWT bearer grant having the roles claims in the following format.
```
"http://wso2.org/claims/role": "[\"Internal\\/subscriber\",\"Internal\\/creator\",
\"Application\\/admin_DefaultApplication_PRODUCTION\",\"Internal\\/publisher\",
\"Internal\\/everyone\",\"admin\",\"Application\\/test\"]",
"test": "[\"CN=GLS_COMUNICADO_MAR,OU=CLOUD,OU=GROUPS,DC=rg,DC=repsol,DC=com\",
\"CN=GPS_SCCM_ADMLOCAL_CLIENTES_POTENCIAL,OU=GROUPS,DC=rg,DC=repsol,DC=com\"]"
```
With this fix it is corrected as follows
```
"http://wso2.org/claims/role": [
"Internal/subscriber",
"Internal/creator",
"Application/admin_DefaultApplication_PRODUCTION",
"Internal/publisher",
"Internal/everyone",
"admin",
"Application/test"
],
"test": [ …
```
> Handle multi values attributes

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- Resolves https://github.com/wso2/product-is/issues/6743
- Changes to be committed:
- modified:   component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
> Add X509Certificate expiry date check to JWTBearerGrantHandler

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Fix https://github.com/wso2/product-is/issues/7298
> Introduce a configuration to skip enforcing certificate expiry validation

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
Fixes https://github.com/wso2/product-apim/issues/9097
> Fix error in creating a federated user

- pom.xml
Issue:https://github.com/wso2/product-is/issues/9596
PR builder successful: https://jenkins-support-all.wso2.com/jenkins/job/DEV_PR_BUILDER/825/
> Exclude jstl.

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- feature/pom.xml
- pom.xml
$subject
back-porting https://github.com/wso2-extensions/identity-oauth2-grant-jwt/pull/42.
Resolves https://github.com/wso2/product-is/issues/10579.
> Fix error in creating a federated user.

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- pom.xml
$subject
porting https://github.com/wso2-extensions/identity-oauth2-grant-jwt/pull/41.
ASAP
> Introduce a config to disable refresh tokens for jwt-bearer grant

- pom.xml
Change maven url to https in parent pom.
> Change maven url to https

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/cache/JWTCache.java
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/cache/JWTCacheEntry.java
- pom.xml
Move oauth2 jwt cache to tenant space.
Related Issue : https://github.com/wso2/product-is/issues/11690
> Move oauth2 jwt cache to tenant space

- component/grant-type/pom.xml
Add import version range to the pom.
> Add import version range

- pom.xml
-  Introduce version property to the dependencies of the POM by refactoring the code.
Addressing Formatting Issues of the PR : https://github.com/wso2-extensions/identity-oauth2-grant-jwt/pull/49
> Introduce version property to the dependencies of the POM.

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
> [1.1.x] Change dev version to 1.1.0-SNAPSHOT

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
Bump version to 2.2.0-SNAPSHOT
> Bump version to 2.2.0-SNAPSHOT

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
- Refactoring the pom versions to match with the branch.
> [2.1.x] Refactoring pom versions

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
Bump POM versions to major version: 3.0.0 for IPK product.
> Bump pom version to major version

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
> Update 3.0.x branch with latest changes from master

- component/grant-type/pom.xml
- pom.xml
> Update carbon-identity-framework version range

- component/grant-type/pom.xml
- feature/pom.xml
- pom.xml
$Subject
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-
> Changing snapshot version for next release version

- pom.xml
$subject
Related issue: https://github.com/wso2/api-manager/issues/2526
> [2.2.x] Upgrade nimbus to 9.37.3

- component/grant-type/pom.xml
- component/grant-type/src/test/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandlerTest.java
- pom.xml
> [2.2.x] Add jdk11 build support for the repo

- component/grant-type/pom.xml
- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- component/grant-type/src/test/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandlerTest.java
- pom.xml
$Subject
Need to bump oauth version after merging https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2682
Issue - https://github.com/wso2/product-is/issues/21009
> Support scope validation for jwt bearer grant

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
- pom.xml
> Validate jwt depth before processing.
> Validate jwt depth before processing

- component/grant-type/src/main/java/org/wso2/carbon/identity/oauth2/grant/jwt/JWTBearerGrantHandler.java
> Fix possible NPE
